#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertStudents_registration(Students_registration instance);
  partial void UpdateStudents_registration(Students_registration instance);
  partial void DeleteStudents_registration(Students_registration instance);
  partial void InsertLogin(Login instance);
  partial void UpdateLogin(Login instance);
  partial void DeleteLogin(Login instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Students_registration> Students_registrations
	{
		get
		{
			return this.GetTable<Students_registration>();
		}
	}
	
	public System.Data.Linq.Table<Login> Logins
	{
		get
		{
			return this.GetTable<Login>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Students_registration")]
public partial class Students_registration : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Student_Id;
	
	private string _fname;
	
	private string _lname;
	
	private string _gender;
	
	private string _Dob;
	
	private string _address;
	
	private string _accomodation;
	
	private int _mobile;
	
	private int _home;
	
	private string _email;
	
	private string _method;
	
	private string _maritial_status;
	
	private string _ethnicity;
	
	private string _Campus;
	
	private string _faculty;
	
	private string _course;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudent_IdChanging(string value);
    partial void OnStudent_IdChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnDobChanging(string value);
    partial void OnDobChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnaccomodationChanging(string value);
    partial void OnaccomodationChanged();
    partial void OnmobileChanging(int value);
    partial void OnmobileChanged();
    partial void OnhomeChanging(int value);
    partial void OnhomeChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmethodChanging(string value);
    partial void OnmethodChanged();
    partial void Onmaritial_statusChanging(string value);
    partial void Onmaritial_statusChanged();
    partial void OnethnicityChanging(string value);
    partial void OnethnicityChanged();
    partial void OnCampusChanging(string value);
    partial void OnCampusChanged();
    partial void OnfacultyChanging(string value);
    partial void OnfacultyChanged();
    partial void OncourseChanging(string value);
    partial void OncourseChanged();
    #endregion
	
	public Students_registration()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Student_Id
	{
		get
		{
			return this._Student_Id;
		}
		set
		{
			if ((this._Student_Id != value))
			{
				this.OnStudent_IdChanging(value);
				this.SendPropertyChanging();
				this._Student_Id = value;
				this.SendPropertyChanged("Student_Id");
				this.OnStudent_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string lname
	{
		get
		{
			return this._lname;
		}
		set
		{
			if ((this._lname != value))
			{
				this.OnlnameChanging(value);
				this.SendPropertyChanging();
				this._lname = value;
				this.SendPropertyChanged("lname");
				this.OnlnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dob", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Dob
	{
		get
		{
			return this._Dob;
		}
		set
		{
			if ((this._Dob != value))
			{
				this.OnDobChanging(value);
				this.SendPropertyChanging();
				this._Dob = value;
				this.SendPropertyChanged("Dob");
				this.OnDobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accomodation", DbType="VarChar(50)")]
	public string accomodation
	{
		get
		{
			return this._accomodation;
		}
		set
		{
			if ((this._accomodation != value))
			{
				this.OnaccomodationChanging(value);
				this.SendPropertyChanging();
				this._accomodation = value;
				this.SendPropertyChanged("accomodation");
				this.OnaccomodationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="Int NOT NULL")]
	public int mobile
	{
		get
		{
			return this._mobile;
		}
		set
		{
			if ((this._mobile != value))
			{
				this.OnmobileChanging(value);
				this.SendPropertyChanging();
				this._mobile = value;
				this.SendPropertyChanged("mobile");
				this.OnmobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home", DbType="Int NOT NULL")]
	public int home
	{
		get
		{
			return this._home;
		}
		set
		{
			if ((this._home != value))
			{
				this.OnhomeChanging(value);
				this.SendPropertyChanging();
				this._home = value;
				this.SendPropertyChanged("home");
				this.OnhomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_method", DbType="VarChar(50)")]
	public string method
	{
		get
		{
			return this._method;
		}
		set
		{
			if ((this._method != value))
			{
				this.OnmethodChanging(value);
				this.SendPropertyChanging();
				this._method = value;
				this.SendPropertyChanged("method");
				this.OnmethodChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maritial_status", DbType="VarChar(50)")]
	public string maritial_status
	{
		get
		{
			return this._maritial_status;
		}
		set
		{
			if ((this._maritial_status != value))
			{
				this.Onmaritial_statusChanging(value);
				this.SendPropertyChanging();
				this._maritial_status = value;
				this.SendPropertyChanged("maritial_status");
				this.Onmaritial_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ethnicity", DbType="VarChar(50)")]
	public string ethnicity
	{
		get
		{
			return this._ethnicity;
		}
		set
		{
			if ((this._ethnicity != value))
			{
				this.OnethnicityChanging(value);
				this.SendPropertyChanging();
				this._ethnicity = value;
				this.SendPropertyChanged("ethnicity");
				this.OnethnicityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Campus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Campus
	{
		get
		{
			return this._Campus;
		}
		set
		{
			if ((this._Campus != value))
			{
				this.OnCampusChanging(value);
				this.SendPropertyChanging();
				this._Campus = value;
				this.SendPropertyChanged("Campus");
				this.OnCampusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_faculty", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string faculty
	{
		get
		{
			return this._faculty;
		}
		set
		{
			if ((this._faculty != value))
			{
				this.OnfacultyChanging(value);
				this.SendPropertyChanging();
				this._faculty = value;
				this.SendPropertyChanged("faculty");
				this.OnfacultyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course", DbType="VarChar(50)")]
	public string course
	{
		get
		{
			return this._course;
		}
		set
		{
			if ((this._course != value))
			{
				this.OncourseChanging(value);
				this.SendPropertyChanging();
				this._course = value;
				this.SendPropertyChanged("course");
				this.OncourseChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Login")]
public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _password;
	
	private string _role;
	
	private string _name;
	
	private string _email;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
	
	public Login()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string role
	{
		get
		{
			return this._role;
		}
		set
		{
			if ((this._role != value))
			{
				this.OnroleChanging(value);
				this.SendPropertyChanging();
				this._role = value;
				this.SendPropertyChanged("role");
				this.OnroleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
